"""empty message

Revision ID: 268aab002e7f
Revises: c8e05cfe66df
Create Date: 2026-04-08 10:57:04.858442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268aab002e7f'
down_revision = 'c8e05cfe66df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_locations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_locations')
    # ### end Alembic commands ###
